---
title: "Hypothesis Testing"
author: "Lara"
date: "7/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
summary(cars)
```

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
#one sample t test
data<- c(17,16,20,18,16,19,22,13,15,17,21,14,18,12)
result<-t.test(data, mu = 20, alternative = "less", conf.level = 0.99)
result
#to get the t: x-u/s(sqrt(n))
sd(data)
sqrt(14)
-3/(2.94/3.74)
#df- degree of freedom is the total number of data - 1
```
```{r}
#two sample test
data_2<-read.csv("class.csv",header=T)
str(data_2)

```
```{r}
result2<-t.test(data_2$MorningClass, data_2$EveningClass,alternative ="greater")
result2
```
```{r}
data("mtcars")
chi_t<-chisq.test(mtcars$carb, mtcars$cyl)
chi_t
```
```{r}
older<-c(45,38,52,48,25,39,51,46,55,46)
younger<-c(34,22,15,27,37,41,24,19,26,36)
df<-data.frame(older,younger)
str(df)
result<-t.test(df$older,df$younger, alternative="two.sided")
result
```
```{r}
#paired sample t-test
stimulation<-c(12,7,3,11,8,5,14,7,9,10)
no_stimulation<-c(8,7,4,14,6,7,12,5,5,8)
df<-data.frame(stimulation, no_stimulation)
result<-t.test(df$stimulation, df$no_stimulation, alternative="less" ,paired = TRUE)
result
```
```